version: '3'
services:
 broker-rabbitmq:
   image: "rabbitmq:3-management"
   ports:
     - "15672:15672"
   environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
 db-postgres:
   image: "postgres:latest"
   ports:
     - "5444:5432"
   environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=pass